verbose: true
client_info:
    client_list:
    - localhost:8081
    port: 8080
    threads: 5
    wait: false
trace:
    location: ./
    traces:
        - test_data_nginx.json
    limit: 
        type: requests
        amount: 5000
    output: result_nginx_simenc.json

registry:
    - localhost:5009

warmup:
    output: interm_nginx_simenc.json
    threads: 5
    random: false
